run:
	cx\
		graphical2d/graphical.cx\
		graphical2d/screens.cx\
		phx/vector.cx\
		phx/direction.cx\
		\
		graphical3d/graphical.cx\
		graphical3d/boxGeometry.cx\
		graphical3d/sphereGeometry.cx\
		graphical3d/cylinderGeometry.cx\
		graphical3d/circleGeometry.cx\
		\
		models/timer.cx\
		models/cell.cx\
		models/point.cx\
		models/board.cx\
		models/player.cx\
		models/ghost.cx\
		models/game.cx\
		\
		main.cx
