run:
	cx\
		pkg/graphical2d/graphical.cx\
		pkg/graphical2d/screens.cx\
		pkg/graphical2d/screens/game-screen.cx\
		pkg/phx/vector.cx\
		pkg/phx/direction.cx\
		\
		pkg/graphical3d/graphical.cx\
		pkg/graphical3d/boxGeometry.cx\
		pkg/graphical3d/sphereGeometry.cx\
		pkg/graphical3d/cylinderGeometry.cx\
		pkg/graphical3d/circleGeometry.cx\
		\
		internal/models/timer.cx\
		internal/models/cell.cx\
		internal/models/point.cx\
		internal/models/board.cx\
		internal/models/player.cx\
		internal/models/ghost.cx\
		internal/models/game.cx\
		\
		cmd/main.cx
